### ISSUE TITLE
Output size of network not setting correctly 

### ISSUE THREAD

**Issue by GPrathap** [karoldvl/paper-2017-DCASE#1]
root@e82b83a2c15c:/data/paper-2017-DCASE/Code# python ./run_amb.py -D gpu 
Using Theano backend.
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29

Using gpu device 0: GeForce 840M (CNMeM is disabled, cuDNN Mixed dnn version. The header is from one version, but we link with a different version (5110, 6021))
/opt/conda/envs/py35/lib/python3.5/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated since IPython 4.0. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 3110/3110 [00:00<00:00, 30326.38it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████| 400/400 [00:00<00:00, 88027.79it/s]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████| 1170/1170 [00:00<00:00, 87392.23it/s]
Input data parameters: mean = -46.0799, std = 18.322
/opt/conda/envs/py35/lib/python3.5/site-packages/keras/layers/core.py:630: UserWarning: `output_shape` argument not specified for layer softmax and cannot be automatically inferred with the Theano backend. Defaulting to output shape `(None, 15, 1, 451)` (same as input shape). If the expected output shape is different, specify it via the `output_shape` argument.
  .format(self.name, input_shape))
Model layers / shapes / parameters:
- input_1           (None, 1, 200, 500)            0
- conv2d_1          (None, 1, 200, 500)    1,000,100
- batch_normalization_1(None, 100, 1, 451)          400
- leaky_re_lu_1     (None, 100, 1, 451)            0
- dropout_1         (None, 100, 1, 451)            0
- conv2d_2          (None, 100, 1, 451)       10,100
- batch_normalization_2(None, 100, 1, 451)          400
- leaky_re_lu_2     (None, 100, 1, 451)            0
- dropout_2         (None, 100, 1, 451)            0
- conv2d_3          (None, 100, 1, 451)        1,515
- softmax           (None, 15, 1, 451)             0
- global_average_pooling2d_1(None, 15, 1, 451)             0
Total:                                     1,012,515
Epoch 1/500
Traceback (most recent call last):
  File "./run_amb.py", line 94, in <module>
    max_queue_size=10)
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/keras/engine/training.py", line 2147, in fit_generator
    class_weight=class_weight)
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/keras/engine/training.py", line 1833, in train_on_batch
    check_batch_axis=True)
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/keras/engine/training.py", line 1418, in _standardize_user_data
    exception_prefix='target')
  File "/opt/conda/envs/py35/lib/python3.5/site-packages/keras/engine/training.py", line 153, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected global_average_pooling2d_1 to have shape (None, 15) but got array with shape (32, 1)

But still I did not get where went wrong.

**Comment by karolpiczak** [comment]
What version of Keras are you using?

**Comment by GPrathap** [comment]
Environment: Ubuntu 17.04, Python 3.6, Keras 2.1.2

**Comment by GPrathap** [comment]
Can you mention which versions of Keras and Theano you used?

**Comment by karolpiczak** [comment]
I've been using Keras 2.0.8, Theano 0.9.0. I've updated to 2.1.2 and I can indeed reproduce it, thanks. I will look into it.

For the time being you can downgrade Keras and it should work:
`pip install --upgrade Keras==2.0.8`

I will try to fix this after Christmas.

**Comment by GPrathap** [comment]
Thanks

**Comment by YuQingL** [comment]
Hello,
What is the  version of python that this code relies on?  Does Python 2.7 work?

**Comment by karolpiczak** [comment]
It works on 3.6 as it uses f-strings syntax. I would have to take a look at what other issues would need to be modified for 2.7.

**Comment by karolpiczak** [comment]
OK, it seems there were some changes to Keras internals (https://github.com/keras-team/keras/pull/8419) this code wasn't expecting, fixed this.

**Comment by YuQingL** [comment]
karoldvl, thank you!

**Comment by GPrathap** [comment]
Yeap, it works, You can close this issue.

**Comment by karolpiczak** [comment]
Great, thanks for getting back on this.
